---

## Base configure

##Set timezone
- name: set timezone
  shell: timedatectl set-timezone Europe/Moscow

#Install Chrony to time Sync

- name: Synchronize datetime | Install chrony
  apt:
    name: chrony
    state: latest
  tags:
    - backupserver-datesync

#Enable Chrony Services to time Sync

- name: Synchronize datetime | Turn on chronyd
  service:
    name: chronyd
    enabled: yes
    state: started
  notify:
    - systemctl daemon reload
  tags:
    - backupserver-datesync


# Устанавливаем инструменты анализа сети
- name: install base tools
  apt:
    name:
      - traceroute
      - tcpdump
      - net-tools
      - mtr
      - curl
      - iperf3
    state: present
    update_cache: true
  tags:
    - netanalize

# - name: uninstall netplan.io
#   apt:
#     name:
#       - netplan.io
#     state: absent
#     update_cache: true
#   tags:
#     - netplan

 ## Rsyslog Client

- name: Install the latest version of Rsyslog
  ansible.builtin.apt:
    name: rsyslog
    state: latest
  tags:
    - rsyslog-apt-install
    - rsyslog-client-configure

- name: Remove file /etc/rsyslog.d/
  file:
    state: "{{ item }}"
    path: "/etc/rsyslog.d/"
    owner: root
    group: root
    mode: '0755'
  with_items:
    - absent
    - directory
  tags:
    - rsyslog-rules-configure
    - clear-etc-rsyslogd

- name: Remove file /var/log/rsyslog/
  file:
    state: "{{ item }}"
    path: "/var/log/rsyslog/"
    owner: root
    group: root
    mode: '0755'
  with_items:
    - absent
    - directory
  tags:
    - testdelete
    - rsyslog-rules-configure
    - clear-etc-rsyslogd



- name: Copy ./rsyslog.conf to /etc/rsyslog.conf
  copy:
    src: ../files/etc/rsyslog/rsyslog.conf
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify:
    - systemctl daemon reload
    - service restart rsyslog
  tags:
    - rsyslfilesog-client-configure
    - copy-rsyslog-conf


- name: Rsyslog simple template externalshost
  template:
    src: ../files/etc/rsyslog/template/all_logs_externals.conf
    dest: /etc/rsyslog.d/all_logs.conf
  notify:
    - systemctl daemon reload
    - service restart rsyslog
  when:
    - inventory_hostname not in groups["rsysloginternals"]
  tags:
    - rsyslog-client-configure
    - copy-rsyslog-template-alllogs


- name: Rsyslog simple template internalshost
  template:
    src: ../files/etc/rsyslog/template/all_logs_internals.conf
    dest: /etc/rsyslog.d/all_logs.conf
  notify:
    - systemctl daemon reload
    - service restart rsyslog
  when:
    - inventory_hostname in groups["rsysloginternals"]
  tags:
    - rsyslog-client-configure
    - copy-rsyslog-template-alllogs


- name: Restart service rsyslog, in all cases
  ansible.builtin.service:
    name: rsyslog
    state: restarted



  # Configure Audit


# - name: Add line to audit rules about nginx.conf
#   ansible.builtin.lineinfile:
#     path: /etc/audit/rules.d/audit.rules
#     state: present
#     regexp: '^-w /etc/nginx/nginx.conf -p wa -k nginx_conf'
#     line: '-w /etc/nginx/nginx.conf -p wa -k nginx_conf'
#   tags:
#     - audit-configure
#     - configure-nginx

# - name: Add line to audit rules about default.d
#   ansible.builtin.lineinfile:
#     path: /etc/audit/rules.d/audit.rules
#     state: present
#     regexp: '^-w /etc/nginx/default.d/ -p wa -k nginx_conf'
#     line: '-w /etc/nginx/default.d/ -p wa -k nginx_conf'
#   notify:
#     - service auditd restart
#   tags:
#     - audit-configure
#     - configure-nginx


# - name: Install audispd-plugins
#   apt:
#     name: audispd-plugins
#     state: latest
#   tags:
#     - audit-configure


# - name: Add line logformat to auditd.conf
#   ansible.builtin.lineinfile:
#     path: /etc/audit/auditd.conf
#     state: present
#     regexp: "log_format ="
#     line: "log_format = RAW"
#   notify:
#     - service restart auditd
#   tags:
#     - audit-configure


# - name: Add line hosts to auditd.conf
#   ansible.builtin.lineinfile:
#     path: /etc/audit/auditd.conf
#     state: present
#     regexp: "name_format = "
#     line: "name_format = hostname"
# #    line: "name_format = {{ ansible_facts['nodename'] }}"
#   notify:
#     - service restart auditd
#   tags:
#     - audit-configure

# - name: Add line tcplisten to auditd.conf
#   ansible.builtin.lineinfile:
#     path: /etc/audit/auditd.conf
#     state: present
#     regexp: "##tcp_listen_port = 60"
#     line: "tcp_listen_port = 60"
#   notify:
#     - service restart auditd
#   tags:
#     - audit-configure


# - name: Add line change active to /etc/audit/plugins.d/au-remote.conf
#   ansible.builtin.lineinfile:
#     path: /etc/audit/plugins.d/au-remote.conf
#     state: present
#     regexp: "active = no"
#     line: "active = yes"
#   notify:
#     - service restart auditd
#   tags:
#     - audit-configure


# - name: Add line remoteserver to auditd.conf
#   ansible.builtin.lineinfile:
#     path: /etc/audit/audisp-remote.conf 
#     state: present
#     regexp: "remote_server = "
#     line: "remote_server = {{ rsyslog_server }}"
#   notify:
#     - service restart auditd
#   tags:
#     - audit-configure






   