---
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: true   
    eth1:
      addresses:
      - 192.168.255.1/30
      routes:
      - to: 192.168.0.0/16
        via: 192.168.255.2
    eth2:
      addresses:
      - 192.168.56.10/24
