---
- name: Install ZabbixClient
  hosts: allzabbix
  become: True
  gather_facts: True
  roles:
    - "../roles/11_zabbixclient"

  vars:
    zabbix_version: 6.0
    zabbix_repo_url: https://repo.zabbix.com/zabbix/{{ zabbix_version }}/debian/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_version }}-5%2Bdebian12_all.deb
    serverzabbix: "10.99.1.222, 192.168.222.10"
    serveractive: "10.99.1.222, 192.168.222.10"
    zabbix_agent_server: 10.99.1.222
    zabbix_url: http://10.99.1.222
    zabbix_api_use: true 
    zabbix_api_user: Admin
    zabbix_api_pass: Zabbix2023!
    zabbix_interface_port: 10050
    zabbix_host_groups: "Linux servers"
    zabbix_link_templates: "Linux by Zabbix agent"
    zabbix_interface_type: agent 
    zabbix_interface_use_ip: "1" 
    zabbix_interface_ip: ""
    zabbix_host_description: "My linux server" 
    zabbix_host_status: enabled


