---
- name: Install percona to master and slave
  hosts: databases
  become: True
  gather_facts: True
  roles:
    - "../roles/databasepercona"

  vars:
    mysql_version_major: "8"
    mysql_version_minor: "0"
    mysql_password: ipsec2023!
    replica_user: repl
    replica_password: ipsecrepl2023!
    mysql_datadir: "/var/lib/mysql"