---

- name: systemctl daemon reload
  systemd:
    daemon_reload: yes
    

- name: RestartNFTables
  service:
    name: nftables
    state: restarted

- name: start nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
    
- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
    
...