# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "debian/bullseye64"
    config.vm.define "vpnserver" do |vpnserver|
        vpnserver.vm.hostname = "vpnserver"
        vpnserver.vm.network "private_network", ip: "192.168.56.10"
    end
    config.vm.define "vpnclient" do |vpnclient|
        vpnclient.vm.hostname = "vpnclient"
        vpnclient.vm.network "private_network", ip: "192.168.56.20"
    end
  end