---
- name: systemctl daemon reload
  systemd:
    daemon_reload: yes

- name: service restart prometheus
  systemd:
    state: restarted
    name: prometheus

- name: service restart grafana-server 
  systemd:
    state: restarted
    name: grafana-server 