---
- name: systemctl daemon reload
  systemd:
    daemon_reload: yes


- name: restartapache2
  service:
    name: apache2
    state: restarted


- name: start mysql
  service:
    name: mysql
    state: started