# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :inetRouter => {
        :box_name => "debian/bullseye64",
        :vm_name => "inetRouter",
        :net => [
                   { ip: '10.4.111.51', adapter: 1, netmask: "255.255.255.0", virtualbox__intnet: "inet" },
                   { ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net" },
                   #подсеть 192.168.56.0/24 - для связи с vagrant
                   { ip: '192.168.56.10', adapter: 8 },
                ]
  },
  
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.hostname = boxconfig[:vm_name].to_s
        box.vm.provider :virtualbox do |v|
          v.memory = 256 
          v.cpus = 2
        end
        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end

        
        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
      
      # Закомментирован блок, так как настрйка будет выполняться в ansible
      #   case boxname.to_s
      #   when "inetRouter"
      #     box.vm.provision "shell", run: "always", inline: <<-SHELL
      #       sysctl net.ipv4.conf.all.forwarding=1
      #       iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
      #       SHELL
      #   when "centralRouter"
      #     box.vm.provision "shell", run: "always", inline: <<-SHELL
      #       sysctl net.ipv4.conf.all.forwarding=1
      #       echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
      #       echo "GATEWAY=192.168.255.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
      #       systemctl restart network
      #       SHELL
      #   when "centralServer"
      #     box.vm.provision "shell", run: "always", inline: <<-SHELL
      #       echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
      #       echo "GATEWAY=192.168.0.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
      #       systemctl restart network
      #       SHELL
      #  end

      end

  end
  
  
end