# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :inetRouter => {
        :box_name => "debian/bullseye64",
        :vm_name => "inetRouter",
        :net => [
                   #["10.4.111.51", 1, "255.255.255.0", "inet"],
                   [ "192.168.255.1",  2,  "255.255.255.252",  "router-net"],
                   #подсеть 192.168.56.0/24 - для связи с vagrant
                   [ "192.168.56.10", 8, "255.255.255.0",    "mgmt"],
                ]
  },
  :centralRouter => {
        :box_name => "debian/bullseye64",
        :vm_name => "centralRouter",
        :net => [
                   [ "192.168.255.2",  2,  "255.255.255.252",  "router-net"],
                   [ "192.168.0.1",  3,  "255.255.255.240",  "dir-net"],
                   [ "192.168.0.33",  4,  "255.255.255.240",  "hw1-net"],
                   [ "192.168.0.65",  5,  "255.255.255.192",  "wifi-net"],
                   [ "192.168.255.9",  6,  "255.255.255.252",  "office1-central"],
                   [ "192.168.255.5",  7,  "255.255.255.252",  "office2-central"],
                   [ "192.168.56.11",  8, "255.255.255.0",    "mgmt"],
                ]
  },
  
  :centralServer => {
        :box_name => "debian/bullseye64",
        :vm_name => "centralServer",
        :net => [
                   [ "192.168.0.2",  2,  "255.255.255.240",  "dir-net"],
                   [ "192.168.56.12",  8, "255.255.255.0",    "mgmt"],
                ]
  },

  :office1Router => {
        :box_name => "debian/bullseye64",
        :vm_name => "office1Router",
        :net => [
                   [ "192.168.255.10",  2,  "255.255.255.252",  "office1-central"],
                   [ "192.168.2.1",  3,  "255.255.255.192",  "dev1-net"],
                   [ "192.168.2.65",  4,  "255.255.255.192",  "test1-net"],
                   [ "192.168.2.129",  5,  "255.255.255.192",  "managers-net"],
                   [ "192.168.2.193",  6,  "255.255.255.192",  "office1hardware-net"],
                   [ "192.168.56.20",  8, "255.255.255.0",    "mgmt"],
                ]
  },

  :office1Server => {
        :box_name => "debian/bullseye64",
        :vm_name => "office1Server",
        :net => [
                   [ "192.168.2.130",  2,  "255.255.255.192",  "managers-net"],
                   [ "192.168.56.21",  8, "255.255.255.0",    "mgmt"],
                ]
  },

  :office2Router => {
    :box_name => "debian/bullseye64",
    :vm_name => "office2Router",
    :net => [
               [ "192.168.255.6",  2,  "255.255.255.252",  "office2-central"],
               [ "192.168.1.1",  3,  "255.255.255.128",  "dev2-net"],
               [ "192.168.1.129",  4,  "255.255.255.192",  "test2-net"],
               [ "192.168.1.193",  5,  "255.255.255.192",  "office2-net"],
               [ "192.168.56.30",  8, "255.255.255.0",    "mgmt"],
            ]
  },

  :office2Server => {
        :box_name => "debian/bullseye64",
        :vm_name => "office2Server",
        :net => [
                   [ "192.168.1.2",  2,  "255.255.255.128",  "dev2-net"],
                   [ "192.168.56.31",  8, "255.255.255.0",    "mgmt"],
                ]
  },
  
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|
   
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]
      
      box.vm.provider "virtualbox" do |v|
        v.memory = 768
        v.cpus = 1
       end

      # if boxconfig[:vm_name] == "office2Server"
      #  box.vm.provision "ansible" do |ansible|
      #   ansible.playbook = "ansible/provision.yml"
      #   ansible.inventory_path = "ansible/hosts"
      #   ansible.host_key_checking = "false"
      #   ansible.limit = "all"
      #  end
      # end

      boxconfig[:net].each do |ipconf|
        box.vm.network("private_network", ip: ipconf[0], adapter: ipconf[1], netmask: ipconf[2], virtualbox__intnet: ipconf[3])
      end

      # if boxconfig.key?(:public)
      #   box.vm.network "public_network", boxconfig[:public]
      # end

      box.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh
        cp ~vagrant/.ssh/auth* ~root/.ssh
      SHELL

      
      # Закомментирован блок, так как настрйка будет выполняться в ansible
      #   case boxname.to_s
      #   when "inetRouter"
      #     box.vm.provision "shell", run: "always", inline: <<-SHELL
      #       sysctl net.ipv4.conf.all.forwarding=1
      #       iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
      #       SHELL
      #   when "centralRouter"
      #     box.vm.provision "shell", run: "always", inline: <<-SHELL
      #       sysctl net.ipv4.conf.all.forwarding=1
      #       echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
      #       echo "GATEWAY=192.168.255.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
      #       systemctl restart network
      #       SHELL
      #   when "centralServer"
      #     box.vm.provision "shell", run: "always", inline: <<-SHELL
      #       echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
      #       echo "GATEWAY=192.168.0.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
      #       systemctl restart network
      #       SHELL
      #  end
    end
  end
end