---
- name: Copy percona configuration
  copy:
    src: "{{ item }}"
    dest: "/etc/mysql/mysql.conf.d/"
  with_fileglob:
    - files/etc/my.cnf.d/*

- name: Restart MySQL
  service:
    name: mysql
    state: restarted

- name: Copy dump from host machine to local
  copy:
    src: master.sql
    dest: /tmp/master.sql
  
- name: Restore db from dump
  shell: mysql -uroot -p'{{ mysql_password }}' < /tmp/master.sql


# - name: GTID prepare
#   command: >
#     mysql
#       -uroot
#       -p'{{ mysql_password }}'
#       -e 'SET @@GLOBAL.ENFORCE_GTID_CONSISTENCY = WARN'
#   tags: preparegtid

# - name: GTID prepare
#   command: >
#     mysql
#       -uroot
#       -p'{{ mysql_password }}'
#       -e 'SET @@GLOBAL.ENFORCE_GTID_CONSISTENCY = ON'
#   tags: preparegtid

# - name: GTID prepare
#   command: >
#     mysql
#       -uroot
#       -p'{{ mysql_password }}'
#       -e 'SET @@GLOBAL.GTID_MODE = OFF_PERMISSIVE'
#   tags: preparegtid

# - name: GTID prepare
#   command: >
#     mysql
#       -uroot
#       -p'{{ mysql_password }}'
#       -e 'SET @@GLOBAL.GTID_MODE = ON_PERMISSIVE'      
#   tags: preparegtid

# - name: GTID prepare
#   command: >
#     mysql
#       -uroot
#       -p'{{ mysql_password }}'
#       -e 'SET @@GLOBAL.GTID_MODE = ON'  
#   tags: preparegtid



- name: Setup slave
  shell: mysql -uroot -p'{{ mysql_password }}' -e 'CHANGE REPLICATION SOURCE TO SOURCE_HOST="192.168.57.10", SOURCE_PORT= 3306, SOURCE_USER="{{ replica_user }}", SOURCE_PASSWORD="{{ replica_password }}", SOURCE_AUTO_POSITION=1'
  ignore_errors: true
  tags: replstep1

- name: Start SLAVE   
  shell: mysql -uroot -p'{{ mysql_password }}' -e 'START REPLICA;'
  tags: replstep2

#CHANGE REPLICATION SOURCE TO SOURCE_AUTO_POSITION = 1 
#START REPLICA


# CHANGE REPLICATION SOURCE TO 
# SOURCE_HOST='source_server_ip', 
# SOURCE_USER='replica_user', 
# SOURCE_PASSWORD='password', 
# SOURCE_LOG_FILE='mysql-bin.000001', 
# SOURCE_LOG_POS=899; 

