---

## Base configure

- name: Set time zone # \cp /usr/share/zoneinfo/Europe/Moscow /etc/localtime
  copy:
    src: /usr/share/zoneinfo/Europe/Moscow
    dest: /etc/localtime
  tags:
    - rsyslog-server-configure
    - rsyslog-configure
    - set-tz
    - elk-configure


- name: Update Repo url
  shell: "{{item}}"
  with_items: 
    - sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*.repo
    - sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*.repo
  tags:
    - rsyslog-server-configure
    - rsyslog-configure
    - update-base-repo
    - elk-configure


- name: Synchronize datetime | Install chrony
  yum:
    name: chrony
    state: latest
  tags:
    - rsyslog-server-configure
    - rsyslog-configure
    - configure-datetime
    - elk-configure

- name: Synchronize datetime | Turn on chronyd
  service:
    name: chronyd
    enabled: yes
    state: started
  notify:
    - systemctl daemon reload
  tags:
    - rsyslog-server-configure
    - rsyslog-configure
    - configure-datetime
    - elk-configure

 ## Rsyslog Server

- name: Install the latest version of Rsyslog
  ansible.builtin.yum:
    name: rsyslog
    state: latest
  tags:
    - rsyslog-yum-install
    - rsyslog-server-configure

- name: Install the SEManage
  ansible.builtin.yum:
    name: policycoreutils-python-utils
    state: latest
  tags:
    - semanage-yum-install
    - rsyslog-server-configure


- name: Remove file /etc/rsyslog.d/
  file:
    state: "{{ item }}"
    path: "/etc/rsyslog.d/"
    owner: root
    group: root
    mode: '0755'
  with_items:
    - absent
    - directory
  tags:
    - rsyslog-rules-configure
    - clear-etc-rsyslogd

- name: Remove file /var/log/rsyslog/
  file:
    state: "{{ item }}"
    path: "/var/log/rsyslog/"
    owner: root
    group: root
    mode: '0755'
  with_items:
    - absent
    - directory
  tags:
    - testdelete
    - rsyslog-rules-configure
    - clear-etc-rsyslogd


# - name: Rsyslog-server cleaning /etc/rsyslog.d/ and /var/log/rsyslog/
#   shell: "{{item}}"
#   with_items: 
#     - rm -rf /etc/rsyslog.d/*
#     - rm -rf /var/log/rsyslog/*
#   tags:
#     - rsyslog-rules-configure
#     - clear-etc-rsyslogd

- name: Copy ./rsyslog.conf to /etc/rsyslog.conf
  copy:
    src: ../files/etc/rsyslog/rsyslog.conf
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify:
    - systemctl daemon reload
    - service restart rsyslog
  tags:
    - rsyslog-server-configure
    - copy-rsyslog-conf

# - name: Copy ./rsyslogtemplate to /etc/rsyslog.d/*
#   copy:
#     src: ../files/etc/rsyslog/template/
#     dest: /etc/rsyslog.d
#     owner: root
#     group: root
#     mode: u=rw,g=r,o=r
#   notify:
#     - systemctl daemon reload
#     - service restart rsyslog
#   tags:
#     - rsyslog-server-configure
#     - copy-rsyslog-template

- name: Rsyslog Template Otus Style
  template:
    src: ../files/etc/rsyslog/template/{{ file }}
    dest: /etc/rsyslog.d/{{ file }}
  vars:
    file: "otus.conf"
  notify:
    - systemctl daemon reload
    - service restart rsyslog
  tags:
    - rsyslog-server-configure
    - copy-rsyslog-template-otus


- name: Rsyslog | open TCP ports
  shell: "{{item}}"
  with_items: 
    - semanage port -m -t syslogd_port_t -p tcp 514
    - iptables -A INPUT -p tcp --dport 514 -j ACCEPT
    - exit 0
  tags:
    - rsyslog-server-configure
    - rsyslog-enable-tcp
    - open-tcp-ports

- name: Restart service rsyslog, in all cases
  ansible.builtin.service:
    name: rsyslog
    state: restarted

- name: check if rsyslog has port 514 open
  shell: ss -lntup | grep rsyslogd
  register: rsyslog_response
  tags:
    - rsyslog-server-configure
    - test-rsyslog-port

- name: Check port
  fail:
    msg: 'The system detected as fail: 514 doesnt listen'
  when: rsyslog_response.stdout == ""
  tags:
    - rsyslog-server-configure
    - test-rsyslog-port


