---

# Установим gnupg для ключа репозитория

- name: "Install gnupg"
  apt:
    name: gnupg2
    update_cache: yes

# добавим ключ репозитория

- name: Add PostgreSQL apt key
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present


## Добавим репозиторий

- name: Add PostgreSQL repository
  apt_repository:
    repo: deb https://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main
    state: present

# Установим Postgres

- name: Install PostgreSQL 16
  apt:
    name:
      - postgresql-16
    update_cache: yes
    state: present

# Установим Barman

- name: Install PostgreSQL 16
  apt:
    name:
      - barman
      - barman-cli
    update_cache: yes
    state: present



# Установка python-пакетов для модулей psql
- name: install base tools
  apt:
    name:
      - python3-pexpect
      - python3-psycopg2
    state: present
    update_cache: true


# Установка acl
- name: install acl
  apt:
    name:
      - acl
    state: present
    update_cache: true
  tags: repluser

    # Копируем файл .pgpass
- name: copy .pgpass
  template:
    src: "templates/.pgpass.j2"
    dest: /var/lib/barman/.pgpass
    owner: barman
    group: barman
    mode: '0600'


  # Копируем файл barman.conf
- name: copy barman.conf
  template:
    src: "templates/barman.conf.j2"
    dest: /etc/barman.conf 
    owner: barman
    group: barman
    mode: '0755'



