---
- name: systemctl daemon reload
  systemd:
    daemon_reload: yes

- name: service restart rsyslog
  systemd: 
    state: restarted
    name: rsyslog



#[root@pxeserver vagrant]# echo "/usr/share/nginx/html/centos8-install *(ro)" > /etc/exports
#[root@pxeserver vagrant]# exportfs -r

