---
- name: systemctl daemon reload
  systemd:
    daemon_reload: yes

- name: service restart rsyslog
  systemd: 
    state: restarted
    name: rsyslog


- name: RestartNFTables
  service:
    name: nftables
    state: restarted

- name: restartzabbixserver
  service:
    name: zabbix-server
    state: restarted   

