# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :otuslinuxlesson02 => {
        :box_name => "centos/7",
        :ip_addr => '192.168.56.10',
	:disks => {
		:sata1 => {
			:dfile => './sata1.vdi',
			:size => 100,
			:port => 1
		},
		:sata2 => {
                        :dfile => './sata2.vdi',
                        :size => 100, # Megabytes
			:port => 2
		},
                :sata3 => {
                        :dfile => './sata3.vdi',
                        :size => 100,
                        :port => 3
                },
                :sata4 => {
                        :dfile => './sata4.vdi',
                        :size => 100, # Megabytes
                        :port => 4
                },
                :sata5 => {
                        :dfile => './sata5.vdi',
                        :size => 100, # Megabytes
                        :port => 5
                }

	}

		
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            	  vb.customize ["modifyvm", :id, "--memory", "1024"]
                  needsController = false
		  boxconfig[:disks].each do |dname, dconf|
			  unless File.exist?(dconf[:dfile])
				vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                                needsController =  true
                          end

		  end
                  if needsController == true
                     vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
                     boxconfig[:disks].each do |dname, dconf|
                         vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                     end
                  end
          end
 	  box.vm.provision "shell", inline: <<-SHELL
	      mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
              yum install https://repo.ius.io/ius-release-el7.rpm https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
              yum update
	      yum install -y mdadm smartmontools hdparm gdisk
              echo "LSBLK"
              lsblk
	      echo "Start create RAID 5"
              echo "Erase superblocks"
              sudo mdadm --zero-superblock --force /dev/sd{b,c,d,e,f}
              echo "Create RAID 5"
              sudo mdadm --create --verbose /dev/md0 -l 5 -n 5 /dev/sd{b,c,d,e,f} 
              echo "Wait a little time to create RAID"              
              sleep 5
              sudo mkdir /etc/mdadm
              sudo -s
              echo "DEVICE partitions" > /etc/mdadm/mdadm.conf
              echo "MDADM.conf"
              sudo mdadm --detail --scan --verbose | awk '/ARRAY/ {print}' >> /etc/mdadm/mdadm.conf
              cat /etc/mdadm/mdadm.conf
              echo "Create partition"
              sudo parted -s /dev/md0 mklabel gpt
              sudo parted /dev/md0 mkpart primary ext4 2048KiB 20%
              sudo parted /dev/md0 mkpart primary ext4 20% 40%
              sudo parted /dev/md0 mkpart primary ext4 40% 60%
              sudo parted /dev/md0 mkpart primary ext4 60% 80%
              sudo parted /dev/md0 mkpart primary ext4 80% 100%
              echo "Create Filesystem"
              for i in $(seq 1 5); do sudo mkfs.ext4 /dev/md0p$i; done
              sudo mkdir -p /raid/part{1,2,3,4,5}
              echo "Mount part to folders"
              for i in $(seq 1 5); do sudo mount /dev/md0p$i /raid/part$i; done
              echo "Create /etc/fstab"
              for i in $(seq 1 5); do sudo echo '/dev/md0p'$i' /raid/part'$i' ext4    defaults 1 2' | sudo tee -a /etc/fstab; done
              sleep 5
              cat /etc/fstab
              cat /proc/mdstat
              echo "LSBLK"
              lsblk
  	  SHELL

      end
  end
end

