---
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: true
    eth1:
      dhcp4: false
    eth2:
      dhcp4: false   
    eth3:
      addresses: [192.168.255.9/30]
    eth4:
      addresses: [192.168.56.11/24]
    #Set LACP
  bonds:
    bond0:
      dhcp4: no
      interfaces: [eth1, eth2]
      addresses: [192.168.255.2/30]
      #gateway4: 192.168.255.1
      parameters:
        mode: 802.3ad
        lacp-rate: fast
        mii-monitor-interval: 100
        #arp-validate: all
