---
- name: Copy percona configuration
  copy:
    src: "{{ item }}"
    dest: "/etc/mysql/mysql.conf.d/"
  with_fileglob:
    - files/etc/my.cnf.d/*
  tags: mysqlconf


- name: "Copy .my.cnf file into the root home folder"
  template:
    src: "templates/my.cnf.j2"
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: Restart MySQL
  service:
    name: mysql
    state: restarted

- name: Copy database dump file
  copy:
    src: etc/bet.dmp
    dest: /tmp/bet.dmp

- name: Restore database
  mysql_db:
    login_user: root
    login_password: "{{ mysql_password }}"
    name: bet
    state: import
    target: /tmp/bet.dmp
    login_unix_socket: /var/run/mysqld/mysqld.sock

# - name: create replication user
#   command: >
#     mysql
#       -uroot
#       -p'{{ mysql_password }}'
#       -e 'CREATE USER "{{ replica_user }}" IDENTIFIED BY mysql -uroot -p'{{ mysql_root_password }}' -e "CREATE USER "{{ replica_user }}"@'%' IDENTIFIED BY "{{ replica_password }}";GRANT REPLICATION SLAVE ON *.* TO 'repl'@'%' IDENTIFIED BY "{{ replica_password }};'


- name: Create database user with name 'repl' and password from vars with all database privileges
  mysql_user:
    login_user: root
    login_password: "{{ mysql_password }}"

    name: "{{ replica_user }}"
    password: "{{ replica_password  }}"
    priv: '*.*:ALL,GRANT'
    state: present
    host: '%'
    login_unix_socket: /var/run/mysqld/mysqld.sock
  tags: repluser



# - name: GTID prepare
#   command: >
#     mysql
#       -uroot
#       -p'{{ mysql_password }}'
#       -e 'SET @@GLOBAL.ENFORCE_GTID_CONSISTENCY = WARN'
#   tags: preparegtid

# - name: GTID prepare
#   command: >
#     mysql
#       -uroot
#       -p'{{ mysql_password }}'
#       -e 'SET @@GLOBAL.ENFORCE_GTID_CONSISTENCY = ON'
#   tags: preparegtid

# - name: GTID prepare
#   command: >
#     mysql
#       -uroot
#       -p'{{ mysql_password }}'
#       -e 'SET @@GLOBAL.GTID_MODE = OFF_PERMISSIVE'
#   tags: preparegtid

# - name: GTID prepare
#   command: >
#     mysql
#       -uroot
#       -p'{{ mysql_password }}'
#       -e 'SET @@GLOBAL.GTID_MODE = ON_PERMISSIVE'      
#   tags: preparegtid

# - name: GTID prepare
#   command: >
#     mysql
#       -uroot
#       -p'{{ mysql_password }}'
#       -e 'SET @@GLOBAL.GTID_MODE = ON'  
#   tags: preparegtid

# - name: Priv to replication user
#   command: >
#     mysql
#       -uroot
#       -p'{{ mysql_password }}'
#       -e 'GRANT REPLICATION SLAVE ON *.* TO "{{ replica_user }}"@"%"'
#   tags: replusergrant

#GRANT REPLICATION SLAVE ON *.* TO repl@"%" IDENTIFIED BY 'testrepl2023!' WITH GRANT OPTION;

- name: Save MySQL dump
  shell: |
    mysqldump > /tmp/master.sql \
      -uroot \
      -p'{{ mysql_password }}' \
      --ignore-table=bet.events_on_demand \
      --ignore-table=bet.v_same_event \
      --all-databases \
      --triggers \
      --routines \
      --master-data
  ignore_errors: true


- name: Get dump from master to host machine
  fetch:
    src: /tmp/master.sql
    dest: master.sql
    flat: yes
...