---
- name: NGINX | Install EPEL Repo package from standart repo
  yum:
    name: epel-release
    state: present
  tags:
    - epel-package
    - packages

- name: NGINX | Install NGINX package from EPEL Repo
  yum:
    name: nginx
    state: latest
  tags:
    - nginx-package
    - packages
  notify:
  - start nginx

- name: Replace nginx.conf
  template:
    src=/templates/nginx.conf.j2
    dest=/etc/nginx/nginx.conf
  tags:
    - nginx-configuration
    - packages
  notify:
    - reload nginx

- name: NGINX | Create my own page
  shell: echo Sincere > /usr/share/nginx/html/index.html
  args:
    executable: /bin/bash  
  tags:
    - nginx-ownpage