
# Описание параметров ВМ
MACHINES = {
  # Имя DV "pam"
  :"pam" => {
              # VM box
              :box_name => "centos/8",
              # Количество ядер CPU
              :cpus => 2,
              # Указываем количество ОЗУ (В Мегабайтах)
              :memory => 1024,
              # Указываем IP-адрес для ВМ
              :ip => "192.168.56.10",
            }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    # Отключаем сетевую папку
    config.vm.synced_folder ".", "/vagrant", disabled: true
    # Добавляем сетевой интерфейс
    config.vm.network "private_network", ip: boxconfig[:ip]
    # Применяем параметры, указанные выше
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.box_version = boxconfig[:box_version]
      box.vm.host_name = boxname.to_s

      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      end
      box.vm.provision "shell", inline: <<-SHELL
          #Разрешаем подключение пользователей по SSH с использованием пароля
          sed -i 's/^PasswordAuthentication.*$/PasswordAuthentication yes/' /etc/ssh/sshd_config
          #Перезапуск службы SSHD
          systemctl restart sshd.service

          # Up the privileges
          sudo -i

          # Create  the users
            sudo useradd otusadmin
            echo "test" | sudo passwd otusadmin --stdin

            sudo useradd otus
            echo "test" | sudo passwd otus --stdin

            # Create the groups

            sudo groupadd -f admin

            # Add users to groups "admin"

            usermod otusadmin -aG admin
            usermod root -aG admin
            #usermod vagrant -aG admin
            # Check a group of users
            cat /etc/group | grep admin

            #create login script
cat >> /usr/local/bin/login.sh << 'EOF'
#!/bin/bash
if [ $(date +%a) = "Sat" ] || [ $(date +%a) = "Sun" ]; then
    if getent group admin | grep -qw "$PAM_USER"; then
        exit 1
    else
        exit 0
    fi
else
    exit 0
fi  
EOF
            #check /usr/local/bin/login.sh
            cat /usr/local/bin/login.sh
            #x privileges
            sudo chmod +x /usr/local/bin/login.sh
            #add string to the /etc/pam.d/sshd 
            echo "account    required     pam_exec.so /usr/local/bin/login.sh" >> /etc/pam.d/sshd
            cat /etc/pam.d/sshd
            #restart ssh
            sudo systemctl restart sshd
            #change the date to saturday 30 sep 2023
            sudo date 093012302023.00
            SHELL
          end
        end
      end      