---
- name: Install psql to slave
  hosts: slave
  become: True
  gather_facts: True
  roles:
    - "../roles/02_slave"


  vars:
    replicator_password: "testrepl2023!"
    allow_world_readable_tmpfiles: true
    master_ip: "192.168.57.10"