---
- name: systemctl daemon reload
  systemd:
    daemon_reload: yes

- name: RestartNFTables
  service:
    name: nftables
    state: restarted

- name: Restart IPSEC
  service:
    name: ipsec
    state: restarted    