# -*- mode: ruby -*-
# vi: set ft=ruby :

# ТРЕБУЕТСЯ ВЫПОЛНИТЬ ЧТОБЫ ВЛЕЗ ISO!!!!  vagrant plugin install vagrant-disksize - чтобы увеличить раздел для  box

Vagrant.configure("2") do |config|

    config.vm.define "pxeserver" do |server|
        config.vm.box = 'centos9/stream'
        config.vm.box_url = 'https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-Vagrant-9-20230116.0.x86_64.vagrant-virtualbox.box'
        config.vm.box_download_checksum = '7a08a97ce54ea55d3294c69353c57db7414512264cdb30377b82748dc2f9f894'
        config.vm.box_download_checksum_type = 'sha256'
        config.disksize.size = '30GB'
            server.vm.host_name = 'pxeserver'
            server.vm.network :private_network,
                            ip: "10.0.0.20",
                            virtualbox__intnet: 'pxenet'

            # server.vm.network "forwarded_port", guest: 80, host: 8081

            server.vm.provider "virtualbox" do |vb|
                vb.memory = "1024"
                vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            end

        
        # config.vm.network "forwarded_port", guest: 80, host: 8888

        # Change Size SDA1
        config.vm.provision "shell", inline: <<-SHELL
                yum install -y cloud-utils-growpart
                parted /dev/sda1 print free
                echo "LSBLK"
                lsblk
                parted /dev/sda print free
                echo 1 > /sys/block/sda/device/rescan
                parted /dev/sda print free
                growpart /dev/sda 1
                resize2fs /dev/sda1
                echo "LSBLK"
                lsblk
                fdisk -l
        SHELL

            # Use ansible to install server
        config.vm.provision :ansible do |ansible|
            ansible.playbook = "playbooks/pxeserver.yml"
        end

    end

    ## Client

 
    # Cent OS 8.2
    # config used from this
    # https://github.com/eoli3n/vagrant-pxe/blob/master/client/Vagrantfile
    config.vm.define "pxeclient" do |pxeclient|
        pxeclient.vm.box = 'centos/7'                       # <------ изначально стоит Сentos 7
        pxeclient.vm.host_name = 'pxeclient'
        pxeclient.vm.network :private_network, ip: "10.0.0.21"
        pxeclient.vm.provider :virtualbox do |vb|
            vb.memory = "2048"
            vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]          

        end
    end
            
end
