---
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: true   
    eth1:
      addresses:
      - 192.168.255.67/29
      routes:
      - to: 0.0.0.0/0
        via: 192.168.255.65        
    eth2:
      addresses:
      - 192.168.56.10/24
