# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINES = {

:gw => {
  :box_name => "generic/debian12",
  :vm_name => "gw",
  :net => [
             [ "10.99.1.254", 2, "255.255.255.0", "WAN1"],
          ]
},

  :node11 => {
        :box_name => "generic/debian12",
        :vm_name => "node11",
        :net => [
                   [ "10.99.1.11", 2, "255.255.255.0", "WAN1"],
                   [ "192.168.11.254", 3, "255.255.255.0", "LAN11"], 
                ]
  },

  :node12 => {
        :box_name => "generic/debian12",
        :vm_name => "node12",
        :net => [
                   [ "10.99.1.12", 2, "255.255.255.0", "WAN1"],
                   [ "192.168.12.254", 3, "255.255.255.0", "LAN12"], 
                ]
  },

  :node13 => {
        :box_name => "generic/debian12",
        :vm_name => "node13",
        :net => [
                   [ "10.99.1.13", 2, "255.255.255.0", "WAN1"],
                   [ "192.168.13.254", 3, "255.255.255.0", "LAN13"], 
                ]
  },


  :node14 => {
        :box_name => "generic/debian12",
        :vm_name => "node14",
        :net => [
                   [ "10.99.1.14", 2, "255.255.255.0", "WAN1"],
                   [ "192.168.14.254", 3, "255.255.255.0", "LAN14"], 
                ]
  },

  :node222 => {
        :box_name => "generic/debian12",
        :vm_name => "node222",
        :net => [
                   [ "10.99.1.222", 2, "255.255.255.0", "WAN1"],
                   [ "192.168.222.254", 3, "255.255.255.0", "LAN222"], 
                ]
  },

  :zabbixserver222 => {
    :box_name => "generic/debian12",
    :vm_name => "zabbixserver222",
    :net => [
               [ "192.168.222.10", 2, "255.255.255.0", "LAN222"],
               [ "192.168.56.10", 3],
            ]
  },

  :node225 => {
        :box_name => "generic/debian12",
        :vm_name => "node225",
        :net => [
                   [ "10.99.1.225", 2, "255.255.255.0", "WAN1"],
                   [ "192.168.225.254", 3, "255.255.255.0", "LAN225"], 
                ]
  },

  :web1 => {
    :box_name => "generic/debian12",
    :vm_name => "web1",
    :net => [
               [ "192.168.225.10", 2, "255.255.255.0", "LAN225"],
            ]
  },

  :web2 => {
    :box_name => "generic/debian12",
    :vm_name => "web2",
    :net => [
               [ "192.168.225.11", 2, "255.255.255.0", "LAN225"],
            ]
  },

  :database1 => {
    :box_name => "generic/debian12",
    :vm_name => "database1",
    :net => [
               [ "192.168.225.20", 2, "255.255.255.0", "LAN225"],
            ]
  },

  :database2 => {
    :box_name => "generic/debian12",
    :vm_name => "database2",
    :net => [
               [ "192.168.225.21", 2, "255.255.255.0", "LAN225"],
            ]
  },

  :backup1 => {
    :box_name => "generic/debian12",
    :vm_name => "backup1",
    :net => [
               [ "192.168.225.40", 2, "255.255.255.0", "LAN225"],
            ]
  },

  :rsyslog1 => {
    :box_name => "generic/debian12",
    :vm_name => "rsyslog1",
    :net => [
               [ "192.168.225.50", 2, "255.255.255.0", "LAN225"],
            ]
  },


}


Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|
   
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]
      
      box.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
       end


      boxconfig[:net].each do |ipconf|
        box.vm.network("private_network", ip: ipconf[0], adapter: ipconf[1], netmask: ipconf[2], virtualbox__intnet: ipconf[3])
      end


      box.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh
        cp ~vagrant/.ssh/auth* ~root/.ssh
      SHELL

    end
  end
end

